---
- hosts: 192.168.56.105
  become: true
  tasks:

  - name: install apache2 package
    yum:
     name: apache2
     state: present

  - name: starting apache2 service
    service:
     name: apache2
     state: started
     enabled: yes
